name: Deploy Staging

on:
  workflow_dispatch:

concurrency:
  group: staging-deploy
  cancel-in-progress: false

jobs:
  deploy:
    environment: 
      name: staging
      url: https://staging.bskye.app
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: "3.99.0"
          command: deploy --name=staging-bskye --route staging.bskye.app --route d-staging.bskye.app